name: Run F1 Analysis Notebook

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install fastf1 pandas numpy matplotlib seaborn jupyter papermill

      - name: Run Notebook
        run: |
          papermill F1_Race_Data_Analysis_.ipynb output.ipynb
